# Generated by Django 5.2.5 on 2025-11-29 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_remove_category_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='is_sale',
            new_name='is_on_sale',
        ),
    ]
